include:
  # include the component located in the current project from the current SHA
  - component: $CI_SERVER_FQDN/$CI_PROJECT_PATH/runner@$CI_COMMIT_SHA
    inputs:
      renovate_version: '39.261.3'
      renovate_image: 'ghcr.io/renovatebot/renovate'

default:
  image:
    name: cloudtooling/dev-buildbox:1.2.1
    entrypoint: [""]

variables:
  RENOVATE_AUTODISCOVER_FILTER: "cloudtooling/**"

stages: [build, test, run, release]

Setup Renovate:
  variables:
    SERVICEACCOUNT_GROUP_ID: 75898119
    GITLAB_TOKEN: $GITLAB_SETUP_TOKEN

Lint Templates and CI Config:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == 'push'
      changes:
        - templates/**/*
        - .gitlab-ci.yml
  script:
    - yamllint -c .yamllint.yml templates/* .gitlab-ci.yml


# If the pipeline is for a new tag with a semantic version, and all previous jobs succeed,
# create the release.
create-release:
  stage: release
  image: registry.gitlab.com/gitlab-org/cli:latest
  script: echo "Creating release $CI_COMMIT_TAG"
  rules:
    - if: $CI_COMMIT_TAG
  release:
    tag_name: $CI_COMMIT_TAG
    description: "Release $CI_COMMIT_TAG of components repository $CI_PROJECT_PATH"
