name: Build

permissions: {}

on:
  pull_request:
  merge_group:
  push:
    branches:
      - develop
    tags:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .yamllint.yml
